/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1e",
        "surface": "#f8f9fb",
        "on-secondary-fixed": "#00210d",
        "surface-dim": "#d9dadc",
        "on-tertiary-fixed": "#2f1500",
        "on-secondary-container": "#00743b",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#474646",
        "primary-container": "#1c1b1b",
        "outline-variant": "#c4c7c7",
        "surface-bright": "#f8f9fb",
        "surface-container-low": "#f3f4f6",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdcc3",
        "surface-container-high": "#e7e8ea",
        "inverse-primary": "#c8c6c5",
        "tertiary": "#000000",
        "secondary-fixed": "#66fe9c",
        "surface-container": "#edeef0",
        "tertiary-container": "#2f1500",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "surface-variant": "#e1e2e4",
        "surface-tint": "#5f5e5e",
        "on-primary": "#ffffff",
        "on-surface-variant": "#444748",
        "secondary": "#006d37",
        "inverse-on-surface": "#f0f1f3",
        "inverse-surface": "#2e3132",
        "outline": "#747878",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed-variant": "#6e3900",
        "primary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#ffb77d",
        "on-secondary-fixed-variant": "#005228",
        "on-tertiary-container": "#c76c00",
        "surface-container-highest": "#e1e2e4",
        "background": "#f8f9fb",
        "on-primary-fixed": "#1c1b1b",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#44e183",
        "on-primary-container": "#858383",
        "secondary-container": "#66fe9c"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "2rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.5rem",
        "gutter": "1rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "margin-tablet": "1.5rem",
        "space-md": "1rem",
        "space-xl": "2rem",
        "space-xxl": "3rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "Roboto", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "numeric-metric": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "numeric-metric": ["30px", { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "500" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
